# Generated by Django 3.2 on 2021-05-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ghvg', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
